from .AB import ABLoss
from .AT import Attention
from .CC import Correlation
from .FitNet import HintLoss
from .FSP import FSP
from .FT import FactorTransfer
from .KD import DistillKL
from .KDSVD import KDSVD
from .NST import NSTLoss
from .PKT import PKT
from .RKD import RKDLoss
from .SP import Similarity
from .VID import VIDLoss
from .CRD import CRDLoss
from .dist_kd import DIST
from .KD import DistillKL_CTKD
from .KD import DistillKL_logit_stand

from .MLLD import MLDLoss
from .FAM import FAMLoss
from .NKD import NKDLoss
